### ISSUE TITLE
Tracking wieviel wovon gekauft wird

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-listBuymenu#11]
- [x] optional über missionConfig einschaltbar
- [x] speichert auf Server profileNamespace
- [x] Tracking pro Buyables-Set, aufgeschlüsselt nach Kategorie
- [x] Anzeige der Statistiken in extra Dialog, über CBA-Admincommand zu öffnen?

**Comment by McDiod** [comment]
Mockup

![trackingmenu_mockup](https://cloud.githubusercontent.com/assets/16549968/23718875/79cad86c-0439-11e7-8a6d-a8663040e910.png)

**Comment by McDiod** [comment]
- [x] Dialog Grundgerüst
- [x] Sidebar
- [x] Graph (fn_updateMain.sqf)

**Comment by McDiod** [comment]
eff9f53bf2fcece111fc073591f4b6246c8fd18b
